### ISSUE TITLE
Multiplayer desyncs back to Day 1

### ISSUE THREAD

**Issue by Firewito** [Robosturm/Commander_Wars#1437] opened 2023-02-21 19:38 UTC
**Describe the bug**
While playing Multiplayer in the server with an android guy, in several matches we got the desync message and when reconnecting we saw that we were back to Day 1, trying to do a move showed the desync message again, and trying to reconnect would send us back to Day 1 again.

**Expected behavior**
Desync shouldnt send us back that many turns.

**Screenshots**
We were in day 7, then the desync sent us to day 1:
![was_the_first_match](https://user-images.githubusercontent.com/113127747/220440581-f8becfa1-4ee5-41af-afee-cba7ab6d3666.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 | Idk what the android guy had.
 - Version: 29.1
 - Active Mods: None

**Additional context**
The android guy might have set cows to second plane for a bit, still even with doing that this thing didnt happen before (Pretty sure).

**Comment by Robosturm** [comment] 2023-02-22 17:23
The server sends you back to the state currently active on the server.
Probably is a duplicate of  #1441

**Closed by Robosturm** 2023-02-22 17:23 UTC
Labels: invalid
