### ISSUE TITLE
Crash when no CO is within 1st slot when game starts

### ISSUE THREAD

**Issue by HappyPotatoFunTime** [Robosturm/Commander_Wars#346] opened 2020-10-28 07:08 UTC
It is as it says. When the 1st CO of a faction is "empty" (X), the game will crash on startup of a match. Even when changing the faction type from "CO's" to any other (Blue Moon, Green Earth, etc), it will still crash.

This by no means affects gameplay, as the 1st CO slot can be filled with the faction CO (the ones with faction symbol), though can be unexpected when starting new games forgetting to set up AI.

**Comment by Robosturm** [comment] 2020-10-28 09:01
Could you please attach the crash report?
I can't reproduce the crash at the moment. 
Thx

**Comment by Robosturm** [comment] 2020-10-28 18:39
Did you apply the hotfix?

**Comment by Robosturm** [comment] 2020-10-29 21:11
Assumed to be fixed in the hotfix version.

**Closed** 2020-10-31 20:33 UTC
Labels: bug, fixed/done
