### ISSUE TITLE
consistent naming of tags

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Robosturm/Commander_Wars#1455] opened 2023-02-26 15:53 UTC
**Is your feature request related to a problem? Please describe.**
I have [automated](https://github.com/LuckyTurtleDev/aur-auto-update-ci) the update of the [aur](https://aur.archlinux.org/packages/commander-wars) package. But commander wars does not use a consistent naming scheme for the release tags.
This can cause the update to fail, or even worse leads to a wrong pkgver.
For example commander-wars has use the following tags in history:
```
"Beta_29_3_Build1", "Beta_29_2_Build1", "Beta_29_1_Build1", "Beta_29_Build2", "Beta28_Build2", "Beta27_Build3", "Beta_26_1_Build-5", "Beta_26_Build-1", "Beta_25_1_AndroidTest1", "Beta_25_5", "Beta_24_2", "Beta_24_1", "Beta_24", "Beta_23", "Beta_22_7", "Beta_25_6", "Beta_22_5_v2", "Beta_22_3_1", "Beta_22_2_v2", "Beta_21_4_Hotfix", "Beta_21_3", "Beta_21_1", "Beta_20", "Beta_19", "Beta_18_1", "Beta_18", "Beta_17", "Beta_16", "Beta_15", "Beta_14"
```
This leads the following naming scheme for the pkgver:
```
_pkgtag=Beta_29_3_Build1 #auto updated by CI
                                    #current tag    (original tag)      -> new tag
pkgver=${_pkgtag/Beta_/0_}          #Beta_25_5      (Beta_25_5)         -> 0_25_5
pkgver=${pkgver/Beta/0_}            #Beta28_Build2  (Beta28_Build2)     -> 0_28_Build2
pkgver=${pkgver/_Build-/_Build}     #0_26_1_Build-5 (Beta_26_1_Build-5) -> 0_26_1_Build5
pkgver=${pkgver/_Build/_}           #0_27_Build3    (Beta27_Build3)     -> 0_27_3
pkgver=${pkgver//_/.}               #0_26_1_5       (Beta_26_1_Build-5) -> 0.26.1.5
```

**Describe the solution you'd like**
Consistent naming of tags. For example simple tags like `v0.29.3.1`, which are used by many projects. But the current naming scheme is also fine, **as long as it does not change again.**

**Describe alternatives you've considered**
More bash naming syntax :thinking: ?

**Comment by Robosturm** [comment] 2023-03-01 16:46
I'll try to bare that in mind for the future.
And use the latest Tag-Variant Beta_29_3_Build1
The problem is that the creation of a release still involves a couple of manual steps.

Also note that a release should only be published once a release has been marked as latest version.
Before that a release is still in a dev state

**Comment by LuckyTurtleDev** [comment] 2023-03-01 19:16
Thanks

>Also note that a release should only be published once a release has been marked as latest version.
Before that a release is still in a dev state

Prereleases will be ignored by the ci.

**Closed** 2023-03-16 14:17 UTC
Labels: enhancement
