### ISSUE TITLE
Banlist Issues?

### ISSUE THREAD

**Issue by FranticFairy** [Robosturm/Commander_Wars#866] opened 2022-03-07 18:17 UTC
When I try and save a unit banlist, it doesn't appear in the dropdown list alongside the default banlists.

**Comment by Robosturm** [comment] 2022-03-07 18:40
That's not fully correct the list is only update once you reenter the menu but not when saving it.
Therefor i marked it as improvement and not a bug

**Closed** 2022-03-07 19:58 UTC
Labels: enhancement, fixed/done
