### ISSUE TITLE
Game end 1 day late

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#488] opened 2021-06-28 19:59 UTC
on AWBW map Caustic Finale I beat the game on Day 15 but it processed the enemy's turn then started my turn on day 16 before ending the game.

recieved a error for cannot call method removeUnit
[console.log](https://github.com/Robosturm/Commander_Wars/files/6728953/console.log)

ignore the hvy tank bs... thats my doing...lol

![endgame error](https://user-images.githubusercontent.com/75344715/123696382-8d803c80-d810-11eb-85e1-1c9891d36946.png)

the effect on the graph though is nice, I like that the game shows the whole win icon without being cut off by the side of the graph when the game ends.

**Comment by Robosturm** [comment] 2021-06-29 14:30
What mods did you use on top of that?
Cause i'm only searching for bugs related to vanilla mods or the vanilla game.
So the problem might get caused by some weird mod interaction....

**Comment by TeslaTrooper09** [comment] 2021-06-29 17:51
just aw2 image mod, aw af mod, and the reskin mod, i replayed it stock, no issue, so i guess my issue's fake news...lol

**Comment by Robosturm** [comment] 2021-06-30 08:14
It looks like a problem with hq capture, but it's either fixed in the current release or is somewhat related to aw af mod would be my guess....

**Closed** 2021-09-14 14:53 UTC
Labels: bug, fixed/done
