### ISSUE TITLE
Ability to Hide Units and Tiles in Map Preview for Fog of War and Shroud of War maps

### ISSUE THREAD

**Issue by FruityGumGuiltyFruit** [Robosturm/Commander_Wars#1725] opened 2023-12-24 17:11 UTC
**Is your feature request related to a problem? Please describe.**
The map preview reveals the locations of all units and tiles on the map, which makes it easy to "spoil" the contents of a map intended to be played with Fog of War or Shroud of War. Mist of War does not need a change,
Example of preview showing unit location:
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/7aca38ed-0c84-42db-95c3-3a82c998dca0)

**Describe the solution you'd like**
Add an option to the map setting where you can choose to disable seeing units in the preview, so the units should not appear on the map preview.
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/51672790-0ee4-42e7-b450-badb59108687)

Example of what a Fog of War preview might look like:
![image](https://github.com/Robosturm/Commander_Wars/assets/142738275/d6726dfb-aa06-4fa6-a6ba-472913c2296b)

If a map is marked as "Shroud of War", the map and the units should not appear on the map preview. I created a new texture for this.
Example of the texture:
![example shroud of war 3](https://github.com/Robosturm/Commander_Wars/assets/142738275/34571ef1-1ac3-4003-9f77-c7025dde9211)
Here is the file.
[minimap_hidden.zip](https://github.com/Robosturm/Commander_Wars/files/13762414/minimap_hidden.zip)

**Describe alternatives you've considered**
Maybe a setting in the options menu to give the player the option to view the preview as normal, if they dislike it being hidden.

**Comment by Robosturm** [comment] 2023-12-24 21:46
The issue is that even if a map is marked as fow or shroud:
a) you have a way to get better information by simply changing them in the rules
b) You may cheat to get those infornation e.g replay the map to avoid frustrating game information.

So I'm not really convinced of that suggestion. I know what you want but I think it's not leading to a better gaming experience

**Comment by Robosturm** [comment] 2024-01-04 08:34
Since you didn't get around with an argument why I'm wrong or why it's still a good idea. I'm closing this request.

**Closed by Robosturm** 2024-01-04 08:34 UTC
