### ISSUE TITLE
Request: Replace instances of generic names for 'Player n' on the interface, change for Player name variable

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#1457] opened 2023-02-28 00:50 UTC
**Is your feature request related to a problem? Please describe.**
Currently, in some parts of the interface, such as the game info window, there are references to the player number instead of the player name. It might be ideal to replace these by the name set by the user, to make it clear. 

**Describe the solution you'd like**
Changing instances of the interface where the users are referred by number and instead switch it to the player name or Player Name(Player number). This would make it easier to understand for newcomers, as well as spectators of a match.

**Comment by Robosturm** [comment] 2023-03-01 16:48
Removing the number won't happen, since e.g. an ai always gets the same.
If you give me a list of affected ui's and I take a look at it if adding the name after Player N is doable.

**Comment by lonewolf19991** [comment] 2023-03-03 03:13
This one is the first one that comes to mind:
![Screenshot from 2023-03-02 13-23-58](https://user-images.githubusercontent.com/96459683/222621946-4c923707-7297-472c-b4c2-7d9e455f6fbb.png)

These might be obvious for 2 player maps, but when you have multiple players like 4 or more, might be ideal to change it to the player name, since sometimes it's not always easy to remember all the factions and colors. 
![Screenshot from 2023-03-02 13-28-52](https://user-images.githubusercontent.com/96459683/222621964-5b20bfd5-71e7-425b-8181-de4b9478f928.png)
![Screenshot from 2023-03-02 13-35-25](https://user-images.githubusercontent.com/96459683/222621998-30d7a3a4-4d20-49c9-81b1-ebe5d19d8090.png)

**Comment by Robosturm** [comment] 2023-03-03 15:19
@lonewolf19991 
In all those places replacing Player 2 doesn't work. :(
The problem is that the same username can be assigned to  multiple players. So changing Player n with username results in an information loose.
For the two menu i can offer to add a tooltip when hovering over player n and or the hq showing the username.
But for the last screen there's no real solution. Sadly.

Are you fine with those to changes? Else I'll close that issue.

**Comment by lonewolf19991** [comment] 2023-03-03 16:12
Yes, that's fine, thank you.

**Closed** 2023-03-04 09:02 UTC
Labels: enhancement, fixed/done
