### ISSUE TITLE
Unable to target meteors in DoR campaign a heros farewell (Android)

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#560] opened 2021-09-19 11:35 UTC
![Screenshot_20210918-223757](https://user-images.githubusercontent.com/75344715/133925939-73cab4d3-9a98-469c-943a-4ec0763a67d1.jpg)

unable to target meteors with any units.

the game recognizes it can fire but will not select with the red block once fire action has been pressed

**Comment by Robosturm** [comment] 2021-09-19 11:45
Duplicate of #554

**Closed by Robosturm** 2021-09-19 11:45 UTC
Labels: bug, duplicate, Confirmed
