### ISSUE TITLE
have a bug where in war room has random weather 

### ISSUE THREAD

**Issue by ringtaill99** [Robosturm/Commander_Wars#1607] opened 2023-05-11 18:30 UTC
**Describe the bug**
it happened after i clicked on repaly game for the first time the game thinks i am playing random matches 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Active Mods (Note: none vanilla mod problems want be investigated)

**Additional context**

**Comment by Robosturm** [comment] 2023-05-12 11:31
@ringtaill99 Please when making bug reports delete the things you don't fill out.

Please provide a step by step guide on to create the bug, the issue isn't reproducable on my end.

**Comment by ringtaill99** [comment] 2023-05-12 22:20
i clicked on game replays no replays and then it started to do the bug

**Comment by Robosturm** [comment] 2023-05-13 06:57
@ringtaill99 That's not a step by step guide to reproduce it.

Here's how i can't reproduce it:
1) Start the game
2) Go to personal
3) Press replay game
4) cancel or start a replay and abort it
5) Go to single player
6) Press new campaign
7) Select war room entering the war room
8) Select a map
9) Start the game
10) Check the rules see that random weather is disabled

Please make a step by step guide like this or I have to close this issue as well

**Comment by Robosturm** [comment] 2023-05-15 17:10
No further information was provided so i treat it has a wrong report.

**Closed by Robosturm** 2023-05-15 17:10 UTC
Labels: Not reproducable
