### ISSUE TITLE
Rockets unable to target in DoR a hero's farewell (Android)

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#562] opened 2021-09-19 11:38 UTC
![Screenshot_20210918-223551](https://user-images.githubusercontent.com/75344715/133926030-3ab1a590-8e56-491d-b68c-e2f0dd543a79.jpg)

the rocket launcher is unable to attack the tank during the first turn. once again it recognizes it can fire but you cannot select a target.

**Comment by Robosturm** [comment] 2021-09-19 11:44
Duplicate of #554

**Closed by Robosturm** 2021-09-19 11:44 UTC
Labels: bug, duplicate, Confirmed
