### ISSUE TITLE
Menu buttons issues android

### ISSUE THREAD

**Issue by TeslaTrooper09** [Robosturm/Commander_Wars#1173] opened 2022-11-27 03:07 UTC
menu button text is cut off on smaller resolutions (Note 20) res is full screen, 853 x 384, and the system will not allow it to be adjusted

![Screenshot_20221126-191115](https://user-images.githubusercontent.com/75344715/204117385-57b6b1f3-7c19-499b-9ef8-6b64d8f6183d.jpg)

![Screenshot_20221126-192249](https://user-images.githubusercontent.com/75344715/204117395-d6ab6e02-a2a8-4051-94d4-8f3b5e850c77.jpg)

**Comment by Robosturm** [comment] 2022-11-27 18:56
I fear the problem is related to qt and it's screen resolution detection in your case the fixed top bar showing the clock etc.
Currently qt's screen size detection is buggy which leads to some weird results.
Sadly their's nothing i can do i double checked it on my device and it works fine/correct on it.
Only thing i can do is hope it get's fixed in a qt release.

**Comment by Robosturm** [comment] 2022-11-27 19:00
Note this might got fixed in Qt 6.4.1 but since Qt 6.4.0 had several audio issues i'm not updating to Qt 6.4.1 with the next Patch for Beta 26.

**Comment by Robosturm** [comment] 2023-01-12 18:27
Is it still not working or did the last release with Qt 6.4.2 fix it for you?

**Closed** 2023-05-14 18:06 UTC
Labels: bug, wontfix, Prio Low
