### ISSUE TITLE
Frequent connection lost and game crash during MP games with 3+ players

### ISSUE THREAD

**Issue by wyykak** [Robosturm/Commander_Wars#762] opened 2022-01-26 15:01 UTC
**Describe the bug**
Meet frequent connection lost and game crash during multiplayer games with 3+ human players. Only clients may crash with "EXCEPTION_ACCESS_VIOLATION" in the crash log. Nothing special in the console log. 
_Having 2 human players with AI WILL NOT trigger this problem._

**To Reproduce**
1. Host a MP game with 4+ slots.
2. Connect 2+ clients to the host.
3. Add 1 or more AIs.
4. Play.

**Expected behavior**
The game runs stably.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
We have met this problem from 75fa4d3 to 7834621, with or without mods. I know the information is quite inadequate since I (as the host) have never experienced a crash.
Could you please provide a method to collect more detailed information at runtime, like building the client with special configs?

**Comment by Robosturm** [comment] 2022-01-26 15:18
Duplicate of  #752 also as mentioned in that issue using any in progress states compiled yourself. 
Have no gurantee to be support or to get fixes during the development.

**Closed by Robosturm** 2022-01-26 15:18 UTC
Labels: duplicate
