### ISSUE TITLE
Game crashes right at the start of every battle

### ISSUE THREAD

**Issue by Latiafa** [Robosturm/Commander_Wars#1728] opened 2023-12-27 14:56 UTC
That's about it, it just gives me a crash report every time i try to move.
The os is windows 10, i'm running the precompiled from the releases tab
the file is tecnically the 0.34.2 but it say 0.34.1 in the versions...
at first launch it issued an automatic update
yes i did re-install multiple times...

here is the crash log:

Commander Wars v0.34.1-main Builddate: Dec 25 2023 11:19:45
27 Dec 2023 @ 15:50:10

EXCEPTION_ACCESS_VIOLATION

INFO: 27.12.2023 15:47:19: Started with: C:\Users\Laty\Downloads\Commander_Wars_Release\update\Commander_Wars_Release\..\..\Commander_Wars.exe
INFO: 27.12.2023 15:47:19: Enter "help()" for console info.
INFO: 27.12.2023 15:47:19: Starting Game...
INFO: 27.12.2023 15:47:19: Prepare to Fight...
INFO: 27.12.2023 15:47:19: Read this message while waiting...
INFO: 27.12.2023 15:47:19: 
INFO: 27.12.2023 15:47:19: I still know what you did last summer...
INFO: 27.12.2023 15:47:19: 
CRITICAL: 27.12.2023 15:47:41: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 185
CRITICAL: 27.12.2023 15:47:41: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 190
CRITICAL: 27.12.2023 15:47:41: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 195
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 185
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 190
CRITICAL: 27.12.2023 15:48:11: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 195
CRITICAL: 27.12.2023 15:48:12: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:12: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:12: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:12: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:12: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:13: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:13: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 185
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 190
CRITICAL: 27.12.2023 15:48:14: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 195
CRITICAL: 27.12.2023 15:48:15: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:15: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:15: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:15: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:15: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:16: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:16: TypeError: Cannot call method 'getUnit' of null in File: qrc:/resources/scripts/general/unit.js at Line: 357
CRITICAL: 27.12.2023 15:48:29: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 185
CRITICAL: 27.12.2023 15:48:29: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 190
CRITICAL: 27.12.2023 15:48:29: TypeError: Cannot call method 'getID' of null in File: qrc:/resources/scripts/general/unit.js at Line: 195

**Comment by Robosturm** [comment] 2023-12-27 22:33
Don't use pre-release unless you know how to use them / get told to use one,
They always might be experimental and always try to downgrade to the latest version.
Also this is a duplicate of #1726

**Closed by Robosturm** 2023-12-27 22:33 UTC
Labels: duplicate

**Comment by Latiafa** [comment] 2023-12-29 18:02
ok, avoiding pre-releases, but the regular release also crashed. re-installed again using the latest build, still crashing...

Commander Wars v0.34.2-main Builddate: Dec 27 2023 22:45:24
29 Dec 2023 @ 18:58:39

EXCEPTION_ACCESS_VIOLATION

[0] 0x00007ff65d600e85 ?? ??:0
[1] 0x00007ff65dcb36f3 ?? ??:0
[2] 0x00007ff9d9570d52 ?? ??:0
[3] 0x00007ff9d95714bb ?? ??:0
[4] 0x00007ff9d7fc51d6 ?? ??:0
[5] 0x00007ff9d9539eed ?? ??:0
[6] 0x00007ff9d953d98d ?? ??:0
[7] 0x00007ff9d96c4e8d ?? ??:0
[8] 0x00007ff9d9544d64 ?? ??:0
[9] 0x00007ff9d963614d ?? ??:0
[10] 0x00007ff9d96cbb56 ?? ??:0
[11] 0x00007ffa5f777344 ?? ??:0
[12] 0x00007ffa5ffa26b1 ?? ??:0

INFO: 29.12.2023 18:57:20: Started with: F:\Commander_Wars_Release\Commander_Wars.exe
INFO: 29.12.2023 18:57:20: Enter "help()" for console info.
INFO: 29.12.2023 18:57:20: Starting Game...
INFO: 29.12.2023 18:57:20: Prepare to Fight...
INFO: 29.12.2023 18:57:20: Read this message while waiting...
INFO: 29.12.2023 18:57:20: 
INFO: 29.12.2023 18:57:20: No funny games found :( -> Installing some funny Viruses!
INFO: 29.12.2023 18:57:20:
